CREATE DATABASE IF NOT EXISTS chinese_learning CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chinese_learning;

CREATE TABLE IF NOT EXISTS words (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  hanzi VARCHAR(100) NOT NULL,
  pinyin VARCHAR(150) DEFAULT '',
  meaning VARCHAR(255) NOT NULL,
  lesson VARCHAR(120) DEFAULT '',
  example TEXT,
  note TEXT,
  learned TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
